# Generated by Django 5.1.4 on 2024-12-28 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerai', '0007_roadmaptask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerpath',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='careerpath',
            name='education_requirements',
        ),
        migrations.RemoveField(
            model_name='careerpath',
            name='growth_potential',
        ),
        migrations.RemoveField(
            model_name='careerpath',
            name='salary_range',
        ),
        migrations.RemoveField(
            model_name='careerpath',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='careerpath',
            name='required_skills',
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='careerpath',
            name='required_skills',
            field=models.ManyToManyField(to='careerai.skill'),
        ),
    ]
