# Generated by Django 5.1.4 on 2024-12-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerai', '0008_remove_careerpath_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='path_type',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full Stack Developer'), ('data', 'Data Scientist'), ('mobile', 'Mobile Developer')], default='fullstack', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career_interest',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full Stack Developer'), ('data', 'Data Scientist'), ('mobile', 'Mobile Developer')], default='fullstack', max_length=50),
        ),
    ]
