from django.urls import path
from . import views
from .initial_data import create_initial_data

urlpatterns = [
    path('', views.landing_page, name='landing'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('recommendations/', views.recommendations, name='recommendations'),
    path('recommendations/results/', views.recommendations_results, name='recommendations_results'),
    path('mentors/', views.mentors, name='mentors'),
    path('roadmap/', views.roadmap, name='roadmap'),
    path('about/', views.about, name='about'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('toggle-task/', views.toggle_task, name='toggle_task'),
    path('save-career/', views.save_career_path, name='save_career_path'),
    path('schedule-meeting/', views.schedule_meeting, name='schedule_meeting'),
    path('schedule/<int:mentor_id>/', views.schedule_meeting_view, name='schedule_meeting'),
    path('api/available-slots/<str:date>/', views.get_available_slots, name='available_slots'),
    path('api/schedule-meeting/', views.schedule_meeting, name='schedule_meeting_api'),
    path('meetings/<int:meeting_id>/', views.meeting_detail, name='meeting_detail'),
    path('api/cancel-meeting/<int:meeting_id>/', views.cancel_meeting, name='cancel_meeting'),
    path('meetings/<int:meeting_id>/review/', views.leave_review, name='leave_review'),
    path('api/submit-review/<int:meeting_id>/', views.submit_review, name='submit_review'),
    path('api/update-task/<int:task_id>/', views.update_task, name='update_task'),
    path('api/dashboard-stats/', views.dashboard_stats, name='dashboard_stats'),
    path('api/recent-activities/', views.recent_activities, name='recent_activities'),
    path('api/task-notes/<int:task_id>/', views.task_notes, name='task_notes'),
    path('meetings/', views.meetings, name='meetings'),
    path('api/save-career/', views.save_career, name='save_career'),
    path('career-path/<int:career_id>/', views.career_path_detail, name='career_path_detail'),
    path('skills/', views.skills, name='skills'),
    path('activity/', views.activity, name='activity'),
    path('task/<int:task_id>/complete/', views.complete_task, name='complete_task'),
    path('add-task/', views.add_task, name='add_task'),
]